server:
  port: 8080
spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB # 文件上传大小限制，设置最大值，不能超过该值，否则报错
      max-request-size: 1000MB # 文件最大请求限制，用于批量上传
  redis:
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    #password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

  jackson: # Jackson库配置
    date-format: "yyyy-MM-dd HH:mm:ss" # 设置日期格式为"年-月-日 时:分:秒"
    serialization:
      write-dates-as-timestamps: false # 关闭日期序列化为时间戳的功能
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
#  配置sql日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # typeEnumsPackage or type-enums-package 都可以
  type-enums-package: com.project.template.enums

resetPassword: 123456

jwt:
  secret: "1234567890"
  expire: 2592000000  # 30 days in milliseconds
  issuer: "tokenId"

